import assert from 'node:assert/strict';
import { writeFile, mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { chromium } from '../artifacts/api-server/node_modules/playwright/index.mjs';
import { createServer as createViteServer } from '../artifacts/api-traffic-finder/node_modules/vite/dist/node/index.js';
import { createApp } from '../artifacts/api-server/src/app';
import { analyzeTraffic, browserExecutablePath } from '../artifacts/api-server/src/lib/traffic-analyzer';
import { closeAllInteractiveTrafficSessions } from '../artifacts/api-server/src/lib/interactive-traffic-session';
import { AnalyzeTrafficResponse } from '../lib/api-zod/src/index';
import { startFixture } from './fixture';
import type { Page } from '../artifacts/api-server/node_modules/playwright/index.mjs';

async function main() {
  const checks:string[]=[];
  const fixture=await startFixture();
  const runtime={isPublicHostname:async(host:string)=>host==='127.0.0.1',launchBrowser:()=>chromium.launch({executablePath:browserExecutablePath(),headless:true,args:['--no-sandbox','--disable-dev-shm-usage']})};
  const app=createApp(runtime);
  const server=app.listen(5174,'127.0.0.1');
  await new Promise<void>(resolve=>server.once('listening',resolve));
  const vite=await createViteServer({configFile:fileURLToPath(new URL('../artifacts/api-traffic-finder/vite.config.ts',import.meta.url)),server:{port:5173,strictPort:true,host:'127.0.0.1'}});
  await vite.listen();
  const browser=await runtime.launchBrowser();
  const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});
  const page=await context.newPage();
  const errors:string[]=[];
  page.on('pageerror',error=>errors.push(error.message));
  const pass=(name:string)=>{checks.push(name);console.log(`PASS ${name}`);};
  const post=async(path:string,data:unknown)=>page.request.post('http://127.0.0.1:5173/api'+path,{data});
  const remoteClick=async(x:number,y:number)=>{
    const image=page.getByTestId('capture-remote-screenshot');
    await image.scrollIntoViewIfNeeded();
    const rect=await image.boundingBox();assert(rect);
    await page.mouse.click(rect.x+x/1280*rect.width,rect.y+y/800*rect.height);
  };
  const waitFor=async(fn:()=>Promise<boolean>,name:string)=>{
    const end=Date.now()+12000;
    while(Date.now()<end){if(await fn())return;await page.waitForTimeout(200);}
    throw new Error(`Timeout: ${name}`);
  };
  try {
    await page.goto('http://127.0.0.1:5173/',{waitUntil:'domcontentloaded'});
    await page.getByTestId('status-api-health').getByText('Dienst verbunden').waitFor();
    assert(await page.getByTestId('button-start-analysis').isDisabled());
    await page.getByTestId('input-site-url').fill(fixture.url);
    await page.getByTestId('checkbox-permission').check();
    await page.getByTestId('select-capture-duration').selectOption('3');
    const normalResponse=page.waitForResponse(response=>response.url().endsWith('/api/traffic/analyze'));
    await page.getByTestId('button-start-analysis').click();
    const normalHttp=await normalResponse;
    assert.equal(normalHttp.status(),200);
    const normal=AnalyzeTrafficResponse.parse(await normalHttp.json());
    await page.getByTestId('section-analysis-results').waitFor();
    assert(normal.requests.length>=7);
    assert(normal.counts.fetchXhr>=5);
    assert(normal.counts.rest>=2);
    assert(normal.counts.graphql>=2);
    assert.equal(normal.counts.websocket,1);
    assert(normal.blockedCount>=2);
    const ordinary=normal.requests.find(request=>request.path==='/api/items/1');assert(ordinary);
    assert.equal(ordinary.method,'GET');assert.equal(ordinary.statusCode,200);assert.equal(ordinary.hostname,'127.0.0.1');assert.equal(ordinary.type,'rest');assert(ordinary.durationMs!>=0);
    assert(ordinary.jsonSchema && 'properties' in ordinary.jsonSchema);
    assert.equal((ordinary.jsonSchema.properties as any).price.type,'integer');
    assert.equal(normal.requests.find(request=>request.path==='/query')?.type,'graphql');
    assert.equal(normal.requests.find(request=>request.path==='/api/protected')?.statusCode,403);
    assert.equal(normal.requests.find(request=>request.path==='/xhr-text')?.type,'fetch-xhr');
    assert(!JSON.stringify(normal).includes('FAKE_ONLY'));
    assert(!JSON.stringify(normal).includes('ONLY_A_FAKE_BODY_VALUE'));
    pass('Normal analysis over 5173 → /api proxy → 5174, correct methods/status/host/path/types/durations/schema');
    await page.getByTestId('filter-fetch-xhr').click();
    assert.equal(await page.locator('[data-testid^="row-request-"]').count(),normal.counts.fetchXhr);
    await page.getByTestId('filter-graphql').click();
    assert.equal(await page.locator('[data-testid^="row-request-"]').count(),2);
    await page.getByTestId('filter-all').click();
    await page.getByTestId('input-request-search').fill('price');
    assert(await page.locator('[data-testid^="row-request-"]').count()>=4);
    await page.getByTestId('input-request-search').fill('no_matching_endpoint');
    await page.getByTestId('empty-filtered-requests').waitFor();
    await page.getByTestId('button-clear-search').click();
    await page.getByTestId('filter-api-candidates').check();
    assert(await page.locator('[data-testid^="row-request-"]').count()>0);
    assert(await page.getByTestId('endpoint-group').count()>0);
    pass('Normal API candidates, Fetch/XHR overlap, filters, schema field-name search, empty state and endpoint groups');
    const downloadPromise=page.waitForEvent('download');
    await page.getByTestId('button-export-json').click();
    const download=await downloadPromise;
    const stream=await download.createReadStream();assert(stream);
    const chunks:Buffer[]=[];for await(const chunk of stream)chunks.push(Buffer.from(chunk));
    const text=Buffer.concat(chunks).toString();const exported=JSON.parse(text);
    assert.equal(exported.requestCount,normal.requestCount);
    assert(!text.includes('FAKE_ONLY'));assert(!text.includes('ONLY_A_FAKE_BODY_VALUE'));assert(!text.includes('access_token'));assert(!text.includes('page=2'));
    assert(exported.requests.every((request:any)=>'jsonSchema' in request && !('responseSchema' in request)));
    pass('Real normal JSON download contains only sanitized metadata and value-free jsonSchema');
    const invalidJson=await post('/traffic/analyze',{url:fixture.url+'invalid-json',authorized:true,captureDurationSeconds:3});
    assert.equal(invalidJson.status(),200);const invalidResult=await invalidJson.json();
    assert.equal(invalidResult.requests[0].jsonSchema,null);
    pass('Malformed JSON response returns HTTP 200 with jsonSchema:null instead of HTTP 500');
    const redirect=await post('/traffic/analyze',{url:fixture.url+'redirect',authorized:true,captureDurationSeconds:3});
    assert.equal(redirect.status(),200);assert((await redirect.json()).blockedCount>=1);
    assert(!fixture.seen.some(request=>request.path==='/private'));
    const badOrigin=await page.request.post('http://127.0.0.1:5173/api/traffic/analyze',{headers:{origin:'https://untrusted.example'},data:{url:fixture.url,authorized:true}});
    assert.equal(badOrigin.status(),403);
    const chain=await analyzeTraffic(fixture.url+'redirect-chain',3,runtime);
    assert(chain.blockedCount>=1);assert(!fixture.seen.some(request=>request.path==='/private'));
    pass('Single- and multi-hop redirects to private hosts and foreign browser origins are rejected');
    await page.getByTestId('button-open-interactive-session').click();
    await page.getByTestId('capture-remote-screenshot').waitFor({timeout:30000});
    await waitFor(async()=>Number((await page.getByTestId('capture-request-count').innerText()).match(/\d+/)?.[0])>=7,'initial interactive requests');
    pass('Interactive analysis starts, shows screenshot and polls actual requests');
    // Verify an actual masked screenshot pixel at the fake password field.
    const masked=await page.getByTestId('capture-remote-screenshot').evaluate((image:HTMLImageElement)=>{
      const canvas=document.createElement('canvas');canvas.width=image.naturalWidth;canvas.height=image.naturalHeight;
      const ctx=canvas.getContext('2d')!;ctx.drawImage(image,0,0);return [...ctx.getImageData(130,190,1,1).data];
    });
    assert(masked[0]<65 && masked[1]<75 && masked[2]<65,'Password screenshot field was not masked');
    await remoteClick(80,190);
    const blockedKeyPromise=page.waitForResponse(response=>response.url().endsWith('/api/traffic/session/interact') && response.request().postDataJSON().action==='key');
    await page.getByTestId('capture-remote-viewport').press('a');
    const blockedKey=await blockedKeyPromise;
    assert.equal(blockedKey.status(),400,JSON.stringify(await blockedKey.json()));
    await page.getByTestId('capture-session-error').waitFor();
    pass('Credential input is blocked and masked in the actual screenshot');
    await page.getByTestId('button-toggle-recording').click();
    await page.getByTestId('status-capture-recording').getByText('Pausiert').waitFor();
    const before=(await page.getByTestId('capture-request-count').innerText());
    await remoteClick(80,80);
    await page.waitForTimeout(1500);
    assert.equal(await page.getByTestId('capture-request-count').innerText(),before);
    await page.getByTestId('button-observe-from-here').click();
    await waitFor(async()=>(await page.getByTestId('capture-request-count').innerText()).includes('0 Requests'),'reset record count');
    await page.getByTestId('status-capture-recording').getByText('Aufzeichnung läuft').waitFor();
    await remoteClick(80,80);await remoteClick(80,80);
    await waitFor(async()=>Number((await page.getByTestId('capture-request-count').innerText()).match(/\d+/)?.[0])===2,'two post-reset requests');
    assert.equal(await page.getByTestId('endpoint-group').count(),1);
    assert((await page.getByTestId('endpoint-group').innerText()).includes('/api/items/:id'));
    pass('Pause prevents capture; Ab hier beobachten resets history; resumed clicks group numeric IDs');
    await page.getByTestId('input-capture-search').fill('price');
    assert.equal(await page.locator('[data-testid^="capture-request-"]').count(),3); // two rows plus the request-count label
    await page.getByTestId('capture-filter-graphql').click();
    await page.getByTestId('capture-requests-empty').waitFor();
    await page.getByTestId('capture-filter-fetch-xhr').click();
    await page.getByTestId('capture-filter-api-candidates').check();
    await page.getByTestId('button-clear-capture-search').click();
    pass('Interactive schema field-name search, filters, candidates and empty state');
    // A late response initiated before the reset must never reappear.
    await remoteClick(80,250);
    await page.waitForTimeout(150);
    await page.getByTestId('button-observe-from-here').click();
    await page.waitForTimeout(4200);
    assert((await page.getByTestId('capture-request-count').innerText()).includes('0 Requests'));
    await remoteClick(80,80);
    await waitFor(async()=>(await page.getByTestId('capture-request-count').innerText()).includes('1 Requests'),'new request after late response');
    pass('Ab hier beobachten excludes a genuinely in-flight earlier response');
    // Ordinary search field supports keyboard and submits a real unauthenticated request.
    await remoteClick(80,135);
    await page.getByTestId('capture-remote-viewport').press('p');
    await page.getByTestId('capture-remote-viewport').press('r');
    await page.getByTestId('capture-remote-viewport').press('i');
    await page.getByTestId('capture-remote-viewport').press('c');
    await page.getByTestId('capture-remote-viewport').press('e');
    await page.getByTestId('capture-remote-viewport').press('Enter');
    await waitFor(async()=>fixture.seen.some(request=>request.path==='/api/search'),'ordinary search request');
    pass('Interactive ordinary-field keyboard entry and Enter produce a real request');
    const liveDownloadPromise=page.waitForEvent('download');
    await page.getByTestId('button-export-capture-json').click();
    const liveDownload=await liveDownloadPromise;const liveStream=await liveDownload.createReadStream();assert(liveStream);
    const liveChunks:Buffer[]=[];for await(const chunk of liveStream)liveChunks.push(Buffer.from(chunk));
    const liveText=Buffer.concat(liveChunks).toString();const liveExport=JSON.parse(liveText);
    assert(!('sessionId' in liveExport));assert(!('screenshot' in liveExport));assert(!liveText.includes('FAKE_ONLY'));assert(!liveText.includes('term='));assert(liveExport.requestCount>=1);
    pass('Real interactive JSON download excludes session IDs, screenshots, parameter values and secrets');
    const extra=await post('/traffic/session/start',{url:fixture.url,authorized:true});assert.equal(extra.status(),201);const extraState=await extra.json();
    const limit=await post('/traffic/session/start',{url:fixture.url,authorized:true});assert.equal(limit.status(),429);assert((await limit.json()).error.includes('interactive browser is busy'));
    await post('/traffic/session/end',{sessionId:extraState.sessionId});
    pass('Interactive concurrency limit is enforced without leaking or stopping existing sessions');
    await page.screenshot({path:'test-results/interactive-dashboard.png',fullPage:true});
    await page.getByTestId('button-end-session').click();
    await page.getByTestId('interactive-capture').waitFor({state:'detached'});
    const closed=await page.request.get('http://127.0.0.1:5173/api/traffic/session/state?sessionId='+extraState.sessionId);assert.equal(closed.status(),404);
    assert.equal(fixture.seen.some(request=>request.authorization||request.cookie),false);
    assert.equal(errors.length,0,errors.join('\n'));
    pass('Clean session shutdown, expired-state HTTP 404, no credentials sent, no browser JS errors');
    await page.setViewportSize({width:390,height:844});
    await page.getByTestId('input-site-url').waitFor();
    assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1));
    pass('Mobile viewport has no page-level horizontal overflow');
    await mkdir('test-results',{recursive:true});
    await writeFile('test-results/e2e.json',JSON.stringify({passed:true,executedAt:new Date().toISOString(),checks,requests:normal.requestCount,counts:normal.counts,websocketStatus:normal.requests.find(request=>request.type==='websocket')?.statusCode,fixture:'Real local HTTP/XHR/fetch/GraphQL/WebSocket server; no network or API mocks; fixture host policy injected only into test app.'},null,2)+'\n');
    console.log(`All ${checks.length} E2E checks passed.`);
  } finally {
    await closeAllInteractiveTrafficSessions();await browser.close();await vite.close();server.closeAllConnections();await new Promise<void>(resolve=>server.close(()=>resolve()));await fixture.close();
  }
}
main().catch(error=>{console.error(error);process.exit(1);});
